name: 'Build'
description: 'Build'
inputs:
  workdir:
    description: 'set repo workdir'
    required: true
    default: ''
  repo:
    description: 'repo'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/justforlxz/deepin-builder-docker/archlinux/commit:master'
  args:
    - ${{ inputs.workdir }}
    - ${{ inputs.repo }}
