name: 'Build'
description: 'Build'
inputs:
  workdir:
    description: 'set workdir'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/justforlxz/deepin-builder-docker/archlinux/db:master'
  args:
    - ${{ inputs.workdir }}
