name: 'Build'
description: 'Build'
inputs:
  repo:
    description: 'repo'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/justforlxz/deepin-builder-docker/archlinux/compress:master'
  args:
    - ${{ inputs.repo }}
