name: Create and publish a Docker image

on:
  push:
    paths:
      - 'dev/*'
env:
  REGISTRY: ghcr.io
jobs:
  dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./dev
          push: true
          target: debian-sid
          tags: ghcr.io/justforlxz/deepin-builder-docker/dev:debian-sid
          labels: org.opencontainers.image.title=deepin-builder-docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./dev
          push: true
          target: archlinux
          tags: ghcr.io/justforlxz/deepin-builder-docker/dev:archlinux
          labels: org.opencontainers.image.title=deepin-builder-docker
